-- Generated by docs/plans/parsing_from_old_site/build_step3_import.py
-- EQUESTRIAN_ID_PLACEHOLDER: 5f6496aa-4fe9-42da-a763-29f9bab22d73
-- rows: 25

BEGIN;

INSERT INTO breeds (id, equestrian_id, name, short_name, slug, description, page_data, kind) VALUES
    ('92e16c1e-bbd4-537b-87e6-edb9495f0107'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Башкирская', 'Башкирская', 'bashkirskaya', NULL, '<div></div>', 'horse'),
    ('b116f22e-d926-5578-b4a8-29c074609f57'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Белорусская упряжная', 'Белорусская упряжная', 'belorusskaya-upryazhnaya', NULL, '<div></div>', 'horse'),
    ('b2d3ccba-d97b-59eb-9fc8-399f3a3a22c3'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Буденновская', 'Буденновская', 'budennovskaya', NULL, '<div></div>', 'horse'),
    ('614141ea-0763-5201-ab8a-fbd5227ce654'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Верховая', 'Верховая', 'verhovaya', NULL, '<div></div>', 'horse'),
    ('b97397a5-f74c-56f4-a1d7-f43e70b6c4c7'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Ганноверская', 'Ганноверская', 'gannoverskaya', NULL, '<div></div>', 'horse'),
    ('9b672643-b1f5-570d-9d80-2e97bf4a1afa'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Ганноверская помесь', 'Ганноверская помесь', 'gannoverskaya-pomes', NULL, '<div></div>', 'horse'),
    ('8e3b7267-3f61-5a9b-b59c-85d3adb67133'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Голштинская', 'Голштинская', 'golshtinskaya', NULL, '<div></div>', 'horse'),
    ('86610548-d24c-558c-a927-e6506584b16c'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Забайкальская', 'Забайкальская', 'zabaykalskaya', NULL, '<div></div>', 'horse'),
    ('58c4110e-63ec-54cf-a833-f99d3edf82d6'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Забайкальская кучерявая', 'Забайкальская кучерявая', 'zabaykalskaya-kucheryavaya', NULL, '<div></div>', 'horse'),
    ('9a783bdc-5036-597a-adef-a1426c38353b'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Першерон', 'Першерон', 'persheron', NULL, '<div></div>', 'horse'),
    ('d2608fb6-fa1c-59e7-9071-1358fc59da52'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Полукровная спортивная', 'Полукровная спортивная', 'polukrovnaya-sportivnaya', NULL, '<div></div>', 'horse'),
    ('c9177f30-c03c-5572-9a8d-030b6cfc6a75'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Полукровная спортивная помесь', 'Полукровная спортивная помесь', 'polukrovnaya-sportivnaya-pomes', NULL, '<div></div>', 'horse'),
    ('70a313e6-ba82-5866-b8fb-9f605fe5037a'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Русская верховая', 'Русская верховая', 'russkaya-verhovaya', NULL, '<div></div>', 'horse'),
    ('73d4f61b-571e-5dcc-b9fa-2d5324519b88'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Советский тяжеловоз', 'Советский тяжеловоз', 'sovetskiy-tyazhelovoz', NULL, '<div></div>', 'horse'),
    ('0e1acec4-6da9-5996-b01c-d5cc9bc1118f'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Спортивный пони', 'Спортивный пони', 'sportivnyy-poni', NULL, '<div></div>', 'horse'),
    ('70d58bad-7033-5db3-84ef-98945cd5af7b'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Тракененская', 'Тракененская', 'trakenenskaya', NULL, '<div></div>', 'horse'),
    ('9280d052-2e1c-55b5-b8fe-5e8057c79390'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Тяжеловоз', 'Тяжеловоз', 'tyazhelovoz', NULL, '<div></div>', 'horse'),
    ('117440ee-6113-5168-b890-360d0fc2dc50'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Украинская верховая', 'Украинская верховая', 'ukrainskaya-verhovaya', NULL, '<div></div>', 'horse'),
    ('ff5a21b3-c295-5e9f-b656-b363cba8e847'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Фризская', 'Фризская', 'frizskaya', NULL, '<div></div>', 'horse'),
    ('954724c8-4cb7-51f5-8235-9ec4fc1651ce'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Чистокровная арабская', 'Чистокровная арабская', 'chistokrovnaya-arabskaya', NULL, '<div></div>', 'horse'),
    ('4af87799-cb1a-57b8-9696-3d7127d8f9b8'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Аппалуза пони', 'Аппалуза пони', 'appaluza-poni', NULL, '<div></div>', 'pony'),
    ('9a613d53-9801-5bbe-a73b-c7d213e52408'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Аппалуза-пони', 'Аппалуза-пони', 'appaluza-poni-2', NULL, '<div></div>', 'pony'),
    ('e5290d64-29c7-5211-93f1-38a707113031'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Спортивный пони (pony)', 'Спортивный пони (pony)', 'sportivnyy-poni-pony', NULL, '<div></div>', 'pony'),
    ('c7190645-0c63-5377-b38f-4fce2670ebae'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Уэльский пони', 'Уэльский пони', 'uelskiy-poni', NULL, '<div></div>', 'pony'),
    ('076496bf-bb2d-5450-8618-8f06121a8b99'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Шетлендский пони', 'Шетлендский пони', 'shetlendskiy-poni', NULL, '<div></div>', 'pony');

COMMIT;
