-- Generated by docs/plans/parsing_from_old_site/build_step3_import.py
-- EQUESTRIAN_ID_PLACEHOLDER: 5f6496aa-4fe9-42da-a763-29f9bab22d73
-- rows: 42

BEGIN;

INSERT INTO coat_color (id, equestrian_id, name, short_name, slug, description, page_data) VALUES
    ('488b7977-d542-5162-bdfc-f6d1b005bb54'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Буланая', 'буланая', 'bulanaya', NULL, '<div></div>'),
    ('147521f4-45c2-557c-90c9-4cb7df1de628'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Булано-пегая', 'булано-пегая', 'bulano-pegaya', NULL, '<div></div>'),
    ('76e4e6d4-c1c1-5dab-889c-a7086ca41477'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Бурая', 'бурая', 'buraya', NULL, '<div></div>'),
    ('bb849c86-255d-5321-828e-66506e73c674'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Буро-пегая', 'буро-пегая', 'buro-pegaya', NULL, '<div></div>'),
    ('11ac171b-7774-5e93-bc9a-335833303fbf'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Буро-чубарая', 'буро-чубарая', 'buro-chubaraya', NULL, '<div></div>'),
    ('a0524f66-3980-507d-b06d-6d9b5c465c2f'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Вороная', 'вороная', 'voronaya', NULL, '<div></div>'),
    ('af89bbbe-cfcb-5fd2-83e9-441b0caf2a81'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Вороно-пегая', 'вороно-пегая', 'vorono-pegaya', NULL, '<div></div>'),
    ('7725325e-5096-55a2-9052-1e5ca2e6cac9'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Вороно-чубарая', 'вороно-чубарая', 'vorono-chubaraya', NULL, '<div></div>'),
    ('efb24792-6aa2-5393-91dc-9906fdb4aabc'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Вороной', 'вороной', 'voronoy', NULL, '<div></div>'),
    ('0d73525f-ef44-5918-84bb-5b8729fc22bb'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Гнедая', 'гнедая', 'gnedaya', NULL, '<div></div>'),
    ('2ba6d713-71c9-50d5-ba94-bcbf2de71cc9'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Гнедая в серебре', 'гнедая в серебре', 'gnedaya-v-serebre', NULL, '<div></div>'),
    ('d1c2f3b1-650d-58e2-b75c-cd1e25674f1c'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Гнедо-пегая', 'гнедо-пегая', 'gnedo-pegaya', NULL, '<div></div>'),
    ('46d869cc-6ad9-561b-a745-f6caee1da8d7'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Гнедо-пегая в седину', 'гнедо-пегая в седину', 'gnedo-pegaya-v-sedinu', NULL, '<div></div>'),
    ('3e2e5bcb-79cf-54be-a59b-05d97264da3a'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Золотисто-рыжая', 'золотисто-рыжая', 'zolotisto-ryzhaya', NULL, '<div></div>'),
    ('281d9931-c6b7-5e16-8cba-e9f3a7cdd34d'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Игреневая', 'игреневая', 'igrenevaya', NULL, '<div></div>'),
    ('d0056c53-5455-5fdc-8dad-5b6a049b843c'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Изабелловая', 'изабелловая', 'izabellovaya', NULL, '<div></div>'),
    ('e7cc6e8a-be45-5873-a270-f2031644b21d'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Изабеллово-пегая', 'изабеллово-пегая', 'izabellovo-pegaya', NULL, '<div></div>'),
    ('0808c65a-18ee-5576-953c-120b232ae793'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Изабелово-пегий', 'изабелово-пегий', 'izabelovo-pegiy', NULL, '<div></div>'),
    ('0b6f5ba5-b3d0-5973-b1e1-b2410b6c451e'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Караковая', 'караковая', 'karakovaya', NULL, '<div></div>'),
    ('e6dc7365-88d1-5b95-8bbe-cd646cc38902'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Караково-пегая', 'караково-пегая', 'karakovo-pegaya', NULL, '<div></div>'),
    ('4812920e-a92a-5c4f-9c97-5d0f2ea4313c'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Кауро-розово-чалый', 'кауро-розово-чалый', 'kauro-rozovo-chalyy', NULL, '<div></div>'),
    ('6b9a19d7-695c-5fce-8d4b-d53e95e2b7b6'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Красно-серая', 'красно-серая', 'krasno-seraya', NULL, '<div></div>'),
    ('132cd8bc-8bb6-5847-a872-b23c7d3cae07'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Мышастая', 'мышастая', 'myshastaya', NULL, '<div></div>'),
    ('6290fc60-7d96-5a9d-a37f-a9c33ab8cddf'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Рыжая', 'рыжая', 'ryzhaya', NULL, '<div></div>'),
    ('7b5123d7-d87e-53c1-ad5c-0bbd2b6d9dc1'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Рыже-пегая', 'рыже-пегая', 'ryzhe-pegaya', NULL, '<div></div>'),
    ('da0dba39-1361-5e7d-b574-b426fd4c3c72'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Рыже-пегая в седину', 'рыже-пегая в седину', 'ryzhe-pegaya-v-sedinu', NULL, '<div></div>'),
    ('d09c1f06-2839-5ac0-a1d5-56b09640c8ba'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Рыже-чалая', 'рыже-чалая', 'ryzhe-chalaya', NULL, '<div></div>'),
    ('2155a685-d5ac-56f4-854b-5395ce68b671'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Светло-гнедая', 'светло-гнедая', 'svetlo-gnedaya', NULL, '<div></div>'),
    ('f89bb170-512c-5dac-a152-f2de2506b0b4'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Светло-рыже-саврасая', 'светло-рыже-саврасая', 'svetlo-ryzhe-savrasaya', NULL, '<div></div>'),
    ('b7506d95-2717-58fc-aed0-8cb7ee2cb5d8'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Серая', 'серая', 'seraya', NULL, '<div></div>'),
    ('ec900ff1-f1f2-5d37-be95-f20e796a7fe1'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Серебристо-буланая', 'серебристо-буланая', 'serebristo-bulanaya', NULL, '<div></div>'),
    ('504a0dd7-4f08-54e3-b58d-a1401106341e'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Серебристо-серая', 'серебристо-серая', 'serebristo-seraya', NULL, '<div></div>'),
    ('570d3bf8-ddf8-5baf-a007-304c185f10fd'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Серебристо-соловая', 'серебристо-соловая', 'serebristo-solovaya', NULL, '<div></div>'),
    ('706f5839-7cb9-5a22-ab0d-87c2d35e2d70'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Серо-пегая', 'серо-пегая', 'sero-pegaya', NULL, '<div></div>'),
    ('77328ad3-2f6b-5ca6-9841-16e0afb90e0b'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Соловая', 'соловая', 'solovaya', NULL, '<div></div>'),
    ('685388a6-0097-5142-b7cc-f309ea21a1af'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Солово-пегая', 'солово-пегая', 'solovo-pegaya', NULL, '<div></div>'),
    ('aca79e3f-dc15-504d-9242-06f81b0e412b'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Солово-саврасая', 'солово-саврасая', 'solovo-savrasaya', NULL, '<div></div>'),
    ('69b17ced-9297-5b53-a461-668457b527fd'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Темно-гнедая', 'темно-гнедая', 'temno-gnedaya', NULL, '<div></div>'),
    ('3b2e83e1-88c8-53ba-b96c-2ce0045da524'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Темно-серая', 'темно-серая', 'temno-seraya', NULL, '<div></div>'),
    ('3d05f6b0-b21f-5c22-85c6-2d009a452809'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Темно-соловая', 'темно-соловая', 'temno-solovaya', NULL, '<div></div>'),
    ('7ffef6cd-697f-5b46-b611-e894f94ac95d'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Чубарая', 'чубарая', 'chubaraya', NULL, '<div></div>'),
    ('c96f5804-9808-59cc-ab49-1e3282a25be1'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Чубарая (чепрак)', 'чубарая (чепрак)', 'chubaraya-cheprak', NULL, '<div></div>');

COMMIT;
