-- Generated by docs/plans/parsing_from_old_site/build_step3_import.py
-- EQUESTRIAN_ID_PLACEHOLDER: 5f6496aa-4fe9-42da-a763-29f9bab22d73
-- rows: 40

BEGIN;

INSERT INTO horse_owner (id, equestrian_id, name, description, type, address, phone_numbers) VALUES
    ('71fe05d5-7f43-58a9-af69-27a2d57ce517'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Arina', NULL, 'person', NULL, '[]'::jsonb),
    ('f54861eb-5996-5d95-b2cc-fc05becdc167'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Eisstern A 167', NULL, 'person', NULL, '[]'::jsonb),
    ('716c7266-d22b-51f4-b8d8-fb5c907b1206'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Eva', NULL, 'person', NULL, '[]'::jsonb),
    ('afeb06d8-59de-5bbb-894a-1ee40b1eb6e3'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Eva 1,93', NULL, 'person', NULL, '[]'::jsonb),
    ('fa7565d4-9ec5-56a6-ab36-06b95c219e49'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Favorit S 539', NULL, 'person', NULL, '[]'::jsonb),
    ('cc175530-24fe-5273-a2f1-7df044467559'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Hanny S 19725', NULL, 'person', NULL, '[]'::jsonb),
    ('bbca6693-cc4e-56af-b387-896bf3ef075f'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Kasper S 664', NULL, 'person', NULL, '[]'::jsonb),
    ('6407c041-0228-5fed-afdd-ca0f1445bfe3'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Kate A 253 H', NULL, 'person', NULL, '[]'::jsonb),
    ('4254f1a3-6c6f-50ec-94dc-c9a0bfca4630'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Lilian S 22565', NULL, 'person', NULL, '[]'::jsonb),
    ('5951e392-fbc5-522c-ae27-ac2a11bc4f2c'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Marius A 159', NULL, 'person', NULL, '[]'::jsonb),
    ('4d708b4a-957d-5f0e-892d-315f0a3fb9f6'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Monolith', NULL, 'person', NULL, '[]'::jsonb),
    ('e7e5554e-210f-5653-ab69-7dcc18387b76'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Nico', NULL, 'person', NULL, '[]'::jsonb),
    ('4da85edd-3320-568e-b58a-3122756563b9'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Nico van''t Leestje, Голландия', NULL, 'person', NULL, '[]'::jsonb),
    ('87d69e50-cf0d-59cd-b2bb-608dc2599c03'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Reggi V 80148', NULL, 'person', NULL, '[]'::jsonb),
    ('e353c1a8-c566-588a-af2b-1325f62d94d6'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'SHETLAND PONY', NULL, 'company', NULL, '[]'::jsonb),
    ('9ee99b68-9411-54ca-8f14-3e31b06027bb'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Susi', NULL, 'person', NULL, '[]'::jsonb),
    ('3dab1256-aa0a-5183-9dac-c73bb509451e'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'WELSH PONY', NULL, 'company', NULL, '[]'::jsonb),
    ('b68493db-df1c-5698-a501-8000ddc71a43'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Wildfang A 187', NULL, 'person', NULL, '[]'::jsonb),
    ('920e8da1-8fdd-522a-9091-c07b9471b2e0'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Англия', NULL, 'person', NULL, '[]'::jsonb),
    ('84bbb71e-d2a1-5e67-a392-9d1c99700e2e'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'ГУ "Читинская ГЗК с ипподромом им. Х. Хакимова"', NULL, 'company', NULL, '[]'::jsonb),
    ('ef4236d2-3f21-5199-9112-b6e3ccacd9a9'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Ефимкина Татьяна Николаевна', NULL, 'person', NULL, '[]'::jsonb),
    ('45c0d717-0733-5262-8108-985f2943b2b2'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'ЗАО "Кировский конный завод"', NULL, 'company', NULL, '[]'::jsonb),
    ('7036b4d0-1271-5ad0-a470-0e29d6a23d6d'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'ЗАО "Конный завод "Георгенбург"', NULL, 'company', NULL, '[]'::jsonb),
    ('ece58d82-03c6-5e2b-9a5c-60b2511f2638'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'ЗАО "Хреновской конный завод"', NULL, 'company', NULL, '[]'::jsonb),
    ('ba2a509e-d424-5207-8044-fff31116769d'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Испания', NULL, 'person', NULL, '[]'::jsonb),
    ('f5328f7a-baa1-5483-a9fe-6a8a1ab54a0e'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Конзавод им. С.М.Буденного', NULL, 'person', NULL, '[]'::jsonb),
    ('5e6aba8b-eff2-56f2-b7ea-8b389ed5dd9a'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Конный завод "Орос"', NULL, 'company', NULL, '[]'::jsonb),
    ('111b3d02-2ccc-560a-a00a-d2e823c93daa'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Монахова Ольга Михайловна', NULL, 'person', NULL, '[]'::jsonb),
    ('23096326-9f1f-5679-a2f4-a8c9f1c595c5'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'ООО "Рязанский конный завод"', NULL, 'company', NULL, '[]'::jsonb),
    ('f0783f22-e027-5b3c-bf50-95e44611dac2'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Октябрьский к.з.', NULL, 'company', NULL, '[]'::jsonb),
    ('09b955d8-76c9-557f-9242-851168357331'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Прилепский к/з', NULL, 'company', NULL, '[]'::jsonb),
    ('994581d9-f340-5cf0-8581-78e6ccb590b7'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Спиридонова Ю.М., Маракасова Е.Е.', NULL, 'person', NULL, '[]'::jsonb),
    ('860b005a-8300-5c6e-9d17-a512c5bc25f7'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Чувашский к/з', NULL, 'company', NULL, '[]'::jsonb),
    ('f7c5f065-f00c-5de3-98e1-40716560aebb'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Ягольницкий конный завод', NULL, 'company', NULL, '[]'::jsonb),
    ('6fc3884a-e536-53fe-bac4-184d66ef2ef8'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'Янзина Ю., Маракасова Е.', NULL, 'person', NULL, '[]'::jsonb),
    ('289ff2d1-1e76-50ee-8a12-63b98e083cc3'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'к/ф "Русская тройка"', NULL, 'person', NULL, '[]'::jsonb),
    ('f066736c-ef5c-5bf9-ac20-7be36c80f545'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'с. Зуткулей Дульдургинский р-н', NULL, 'person', NULL, '[]'::jsonb),
    ('1e7e85fb-b595-5d7b-a5be-d47c3ff5af95'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'с. Кункур Агинский р-н', NULL, 'person', NULL, '[]'::jsonb),
    ('529deb65-8ac0-5d85-a22e-c079ca37b0bd'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'с. Чиндалей Дульдургинский р-н', NULL, 'person', NULL, '[]'::jsonb),
    ('0b9e9566-3f9d-516a-88e2-2b28bc85b332'::uuid, '5f6496aa-4fe9-42da-a763-29f9bab22d73'::uuid, 'с. Ю. Аргалей Агинский р-н', NULL, 'person', NULL, '[]'::jsonb);

COMMIT;
